apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # TODO: Replace with your GitHub repo URL
    repoURL: https://github.com/VenkataRKC/k3d-kustomize-poc
    targetRevision: main
    path: apps/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: false   # Don't auto-heal prod — manual approval required
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
