apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # TODO: Replace with your GitHub repo URL
    repoURL: https://github.com/VenkataRKC/k3d-kustomize-poc
    targetRevision: main
    path: apps/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true       # Remove resources deleted from git
      selfHeal: true    # Revert any manual kubectl changes
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
